apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-codgen-jul30test1 
  description: Secure Supply Chain Example for Code Generation Application example that generate code in countless programming languages.   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=test-codgen-jul30test1  
    janus-idp.io/tekton: test-codgen-jul30test1 
    backstage.io/kubernetes-id: test-codgen-jul30test1 
    backstage.io/techdocs-ref: dir:. 
    quay.io/repository-slug: jctestorg/test-codgen-jul30test1
  tags: ["ai", "llamacpp", "vllm", "python"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 